
CREATE TABLE room_type_extension
(
    room_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_room_type_extension PRIMARY KEY (room_type_id)
);

CREATE TABLE room_type_image
(
    room_type_id BIGINT NOT NULL,
    image_url    VARCHAR(1024)
);

CREATE TABLE special_discount
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id         BIGINT                                  NOT NULL,
    discount_date       date                                    NOT NULL,
    discount_percentage DOUBLE PRECISION                        NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_special_discount PRIMARY KEY (id)
);

ALTER TABLE room_type_image
    ADD CONSTRAINT fk_room_type_image_on_room_type_extension FOREIGN KEY (room_type_id) REFERENCES room_type_extension (room_type_id);