CREATE TABLE booking_extension
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id       VARCHAR(100) UNIQUE                                   NOT NULL,
    guest_id            BIGINT                                               NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version             BIGINT                      DEFAULT 0                 NOT NULL,
    
    CONSTRAINT fk_booking_extension_guest
        FOREIGN KEY (guest_id)
            REFERENCES guest_extension (id)
); 