CREATE TABLE special_offer
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version             BIGINT                      DEFAULT 0                 NOT NULL,
    property_id         BIGINT                                                NOT NULL,
    start_date          date                                                  NOT NULL,
    end_date            date                                                  NOT NULL,
    discount_percentage DOUBLE PRECISION                                      NOT NULL,
    title               VARCHAR(100)                                         NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_special_offer PRIMARY KEY (id)
);