CREATE TABLE room_type_amenities
(
    room_type_id BIGINT NOT NULL,
    amenity      VARCHAR(255)
);

CREATE TABLE room_type_extension
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    version        BIGINT                                  NOT NULL,
    rating         DOUBLE PRECISION,
    num_of_reviews BIGINT,
    landmark       VARCHAR(255),
    description    TEXT,
    CONSTRAINT pk_room_type_extension PRIMARY KEY (id)
);

CREATE TABLE room_type_images
(
    room_type_id BIGINT NOT NULL,
    image        VARCHAR(255)
);

ALTER TABLE room_type_amenities
    ADD CONSTRAINT fk_room_type_amenities_on_room_type_extension FOREIGN KEY (room_type_id) REFERENCES room_type_extension (id);

ALTER TABLE room_type_images
    ADD CONSTRAINT fk_room_type_images_on_room_type_extension FOREIGN KEY (room_type_id) REFERENCES room_type_extension (id);