CREATE TABLE promo_code_offer
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id         BIGINT,
    start_date          date                                    NOT NULL,
    end_date            date                                    NOT NULL,
    discount_percentage DOUBLE PRECISION                        NOT NULL,
    title               VARCHAR(255),
    description         VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    version             BIGINT                                  NOT NULL,
    code                VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_promo_code_offer PRIMARY KEY (id)
);

ALTER TABLE promo_code_offer
    ADD CONSTRAINT uc_promo_code_offer_code UNIQUE (code);