CREATE TABLE property_extension
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_number       VARCHAR(50)                                           NOT NULL,
    availability         TEXT                                                  NOT NULL,
    country              VARCHAR(100)                                          NOT NULL,
    surcharge            DOUBLE PRECISION                                      NOT NULL,
    fees                 DOUBLE PRECISION                                      NOT NULL,
    tax                  DOUBLE PRECISION                                      NOT NULL,
    terms_and_conditions VARCHAR(100)                                          NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version              BIGINT                      DEFAULT 0                 NOT NULL
); 