CREATE TABLE guest_extension
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id                  BIGINT UNIQUE                                         NOT NULL,
    traveler_first_name       VARCHAR(100)                                          NOT NULL,
    traveler_last_name        VARCHAR(100)                                          NOT NULL,
    traveler_email            VARCHAR(255) UNIQUE                                   NOT NULL,
    traveler_phone            VARCHAR(50)                                           NOT NULL,
    billing_first_name        VARCHAR(100)                                          NOT NULL,
    billing_last_name         VARCHAR(100)                                          NOT NULL,
    billing_email             VARCHAR(255)                                          NOT NULL,
    billing_phone             VARCHAR(50)                                           NOT NULL,
    billing_mailing_address_1 VARCHAR(255)                                          NOT NULL,
    billing_mailing_address_2 VARCHAR(255),
    billing_city              VARCHAR(100)                                          NOT NULL,
    billing_state             VARCHAR(100)                                          NOT NULL,
    billing_country           VARCHAR(100)                                          NOT NULL,
    billing_zip               VARCHAR(20)                                           NOT NULL,
    special_offers_consent    BOOLEAN                     DEFAULT FALSE             NOT NULL,
    terms_accepted            BOOLEAN                     DEFAULT FALSE             NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version                   BIGINT                      DEFAULT 0                 NOT NULL
); 